version: "3"

services:
    web01:
        image: ${NGINX_IMAGE}
        volumes:
            - ./Server01/src:/sites/src
            - ./Server01/nginx.conf:/etc/nginx/nginx.conf:ro

    web02:
        image: ${NGINX_IMAGE}
        volumes:
            - ./Server02/src:/sites/src
            - ./Server02/nginx.conf:/etc/nginx/nginx.conf:ro

    web03:
        image: ${NGINX_IMAGE}
        volumes:
            - ./Server03/src:/sites/src
            - ./Server03/nginx.conf:/etc/nginx/nginx.conf:ro

    lb:
        image: ${NGINX_IMAGE}
        volumes:
            - ./LoadBalancer/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "8080:80"
